// List of questions
const questions = [
    "What's a kink or fetish you've always wanted to explore but haven't yet?",
    "When was the last time you felt jealous in an ENM dynamic, and how did you handle it?",
    "What’s one thing you wish your primary partner understood better about your kink or ENM needs?",
    "How do you balance your emotional connections with different partners?",
    "What’s the most vulnerable you’ve felt during a scene, and why?",
    "What’s a boundary you've set in ENM that you find challenging to maintain?",
    "If you could rewrite one rule in your current relationship dynamic, what would it be and why?",
    "Have you ever had a kink experience go wrong? How did you and your partner(s) recover from it?",
    "What does aftercare look like for you, and why is it important?",
    "How has exploring ENM changed the way you view love and commitment?",
    "What’s something you’ve learned about yourself through practicing kink?",
    "How do you manage the emotional highs and lows of engaging with multiple partners?",
    "When was the last time you felt deeply connected to someone during a scene? What made it special?",
    "How do you feel when one of your partners gets closer to someone new?",
    "What’s one thing you wish people outside the kink or ENM community understood about your relationships?",
    "How do you establish trust when exploring new dynamics or scenes with a partner?",
    "What’s an emotional boundary you’ve set in ENM that’s been tested, and how did you respond?",
    "How do you navigate jealousy when it arises in your ENM relationships?",
    "How has kink helped you grow as a person, outside of the bedroom?",
    "What’s one fear you have in exploring new kinks or partners?",
    "What’s your favorite type of roleplay scenario, and why?",
    "Have you ever had a threesome or group play that didn’t go as planned? What happened?",
    "What’s the naughtiest location you’ve ever had sex, and would you do it again?",
    "If you could direct a scene with your partner(s), what would it involve?",
    "Would you rather be tied up or tie someone else up? Why?",
    "Have you ever fantasized about one of your partner’s other lovers?",
    "What’s your favorite thing to do to tease someone until they beg?",
    "Have you ever roleplayed as someone’s submissive or dominant outside of a scene? How did it feel?",
    "What’s the most intense impact play you’ve tried, and did you enjoy it?",
    "What’s a safeword that would be a complete turn-on for you?",
    "Have you ever lied about your feelings regarding an ENM experience to avoid conflict?",
    "What’s something you’ve done in a kink scene that surprised even you?",
    "Who is someone outside your current circle you would love to play with, and why?",
    "What’s the longest you’ve gone without sex, and why?",
    "Do you prefer being watched during play or watching others? Explain your choice.",
    "What’s one kink that you’d never try, even for a partner you love?",
    "If you had to choose only one person to be your primary partner for the next year, who would it be and why?",
    "When was the last time you felt possessive in an ENM relationship, and how did you handle it?",
    "Have you ever experienced compersion, and what was it like?",
    "What’s a scene or experience you’ve had that left a lasting impact on your sexuality?",
    "What’s your favorite part of a power exchange dynamic?",
    "How do you feel when you’re in a submissive headspace versus a dominant one?",
    "What’s the most daring position or restraint you’ve tried?",
    "How do you feel about using toys with your partners? Which one is your favorite?",
    "What’s the most extreme form of sensation play you’ve tried, and how did it feel?",
    "If you could take a kink vacation with your partner(s), where would you go and what would you do?",
    "What’s the dirtiest thing you’ve whispered in someone’s ear during a scene?",
    "Have you ever shared one of your partners with another person? How did it feel?",
    "Do you prefer your partner to be rough or gentle when they dominate you?",
    "Have you ever roleplayed a taboo scenario? What was it, and did it turn you on?",
    "If you could pick any celebrity to join you and your partner for a night, who would it be and why?",
    "What’s the one kink that you think defines your sexual identity?",
    "Have you ever tried a double penetration toy or position, and how was it?",
    "What’s your biggest turn-on when watching your partner with someone else?",
    "Would you prefer to be punished for bad behavior or rewarded for obedience? Why?",
    "What’s one fantasy you’ve fulfilled, but wish you could experience for the first time again?",
    "How do you feel about breath play or restriction, and have you ever tried it?",
    "What’s a non-sexual act that turns you on when done in a kink scene?",
    "If you had to be collared by one of your current partners, who would you choose and why?",
    "What’s a limit you thought you had but discovered you enjoy when pushed beyond it?",
    "What’s your favorite spot to be kissed, licked, or teased during play?",
    "If you had to choose, would you rather receive or give a spanking?",
    "Have you ever been caught in the act by someone? How did you react?",
    "What’s the most dominant thing you’ve said or done to someone during a scene?",
    "What’s your favorite form of foreplay during kink sessions?",
    "If you could roleplay as any fictional character with your partner, who would it be and why?",
    "Have you ever used food in a scene? What was the experience like?",
    "What’s your favorite part of a partner’s body to tease, and why?",
    "Do you prefer to be restrained with ropes, cuffs, or something else entirely?",
    "What’s the naughtiest fantasy you’ve yet to act out with a partner?",
    "When was the last time you felt jealous of another person’s connection with your partner, and why?",
    "What’s one rule or boundary in your ENM dynamic that you struggle to follow?",
    "What’s a kink you thought you’d never try but ended up loving?",
    "Do you prefer solo play or group play, and why?",
    "How often do you experience sub-drop or dom-drop, and how do you cope with it?",
    "What’s the most intimate conversation you’ve had with someone while in a scene?",
    "If you could change one thing about your current dynamic with your primary partner, what would it be?",
    "When was the last time you pushed a boundary, and how did it make you feel afterward?",
    "What’s your biggest fear when it comes to exploring kink or ENM dynamics?",
    "What’s a desire you’ve kept secret from your partner(s)?",
    "Have you ever experienced or tried out temperature play? If so, how did it feel?",
    "What’s your favorite kind of lingerie or outfit to wear during a scene?",
    "Have you ever experimented with pain play? What’s your favorite type of pain, if any?",
    "Do you prefer silent obedience or verbal interaction during a scene?",
    "What’s one piece of kink equipment you’ve never used but would love to try?",
    "How does it feel when you’re given a command versus giving one?",
    "What’s your favorite type of edging play, and how long can you last?",
    "Have you ever experienced sensory deprivation, such as blindfolds or noise-canceling headphones?",
    "Do you prefer leather or latex when it comes to outfits and why?",
    "What’s your favorite scene dynamic: teacher/student, master/pet, or something else?",
    "What’s your favorite thing about watching your partner dominate someone else?",
    "What’s the kinkiest request you’ve ever received from a partner?",
    "Would you rather be made to orgasm on command or be denied completely for a night?",
    "What’s the most challenging position you’ve ever been restrained in?",
    "Have you ever roleplayed as someone’s slave or owner? How did it make you feel?",
    "What’s your favorite type of dirty talk to receive or give during a scene?",
    "If you could be part of a BDSM-themed movie or show, which role would you play?",
    "What’s the most intense form of humiliation play you’ve tried or would consider trying?",
    "How do you feel about sharing partners in an ENM dynamic during a group play session?",
    "What’s your favorite way to explore anal play with a partner, and why?"
];


// Function to get a random question
function getRandomQuestion() {
    const randomIndex = Math.floor(Math.random() * questions.length);
    return questions[randomIndex];
}

// Set up event listener for the "Next" button
document.getElementById('nextButton').addEventListener('click', function() {
    const questionCard = document.getElementById('questionCard');
    questionCard.textContent = getRandomQuestion();
});
